---
- name: copy images to load
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - block.tar
    - rhgs-server.tar
    - s3.tar
    - vol.tar

- name: load images
  shell: "docker load < /tmp/{{ item }}"
  with_items:
    - block.tar
    - rhgs-server.tar
    - s3.tar
    - vol.tar

- name: download ose container images
  docker_image:
    name: "{{ image_source }}/{{ item }}"
  with_items:
    - "{{ ose_core_images }}"
    - "{{ ose_infra_images }}"

- name: download cns container images
  docker_image:
    name: "{{ item }}"
  with_items:
    - "{{ cns_core_images }}"

- name: download other images
  docker_image:
    name: "{{ item }}"
  with_items:
    - "{{ other_images }}"

- name: retag images
  docker_image:
    name: "{{ image_source }}/{{ item }}"
    repository: "localhost:5000/{{ item }}"
    push: yes
  with_items:
    - "{{ ose_core_images }}"
    - "{{ ose_infra_images }}"

- name: retag images
  docker_image:
    name: "{{ item }}"
    repository: "localhost:5000/{{ item }}"
    push: yes
  with_items:
    - "{{ cns_core_images }}"
    - "{{ other_images }}"

- name: retag images
  docker_image:
    name: "{{ upstream_cns_mirror }}/rhgs3/rhgs-server-rhel7:3.3.1-9"
    repository: "localhost:5000/rhgs3/rhgs-server-rhel7:3.3.1-9"
    push: yes

- name: retag images
  docker_image:
    name: "{{ upstream_cns_mirror }}/rhgs3/rhgs-s3-server-rhel7:3.3.1-6"
    repository: "localhost:5000/rhgs3/rhgs-s3-server-rhel7:3.3.1-6"
    push: yes

- name: retag images
  docker_image:
    name: "{{ upstream_cns_mirror }}/rhgs3/rhgs-gluster-block-prov-rhel7:3.3.1-6"
    repository: "localhost:5000/rhgs3/rhgs-gluster-block-prov-rhel7:3.3.1-6"
    push: yes

- name: retag images
  docker_image:
    name: "{{ upstream_cns_mirror }}/rhgs3/rhgs-volmanager-rhel7:3.3.1-7"
    repository: "localhost:5000/rhgs3/rhgs-volmanager-rhel7:3.3.1-7"
    push: yes
...
