---
  - name: enable extras
    shell: subscription-manager repos --enable rhel-7-server-extras-rpms

  - name: install docker
    yum: name=etcd state=present

  - name: disable extras
    shell: subscription-manager repos --disable rhel-7-server-extras-rpms

...
