---

# vim: set ft=ansible:

  - name: Pulling the workshopper docker image
    docker_image:
      name: quay.io/osevg/workshopper@sha256:c40b92f5d257134807fd9ff1443ff2456c683e9126f7710524a5f28763375264

  - name: put the systemd-docker binary file at /usr/bin
    copy:
      src: systemd-docker
      dest: /usr/local/sbin/
      mode: u=rx,g=r,o=r
      owner: root
      group: root

  - name: create workshopper systemd service
    copy:
      src: workshopper.service
      dest: /etc/systemd/system/

  - name: copy the config file containing environment variables and URLs
    copy:
      src: workshopper
      dest: /etc/sysconfig/

...
