apiVersion: v1
kind: Template
metadata:
  name: machine-autoscaler-template
parameters:
- name: MACHINESET
  displayName: Machineset
  description: The name of the Machineset to autoscale
  required: true
objects:
- apiVersion: autoscaling.openshift.io/v1beta1
  kind: MachineAutoscaler
  metadata:
    name: machineautoscaler
    namespace: openshift-machine-api
  spec:
    minReplicas: 1
    maxReplicas: 2
    scaleTargetRef:
      apiVersion: machine.openshift.io/v1beta1
      kind: MachineSet
      name: "${MACHINESET}"
