---
  - name: create docker storage config
    copy: src=idm-install dest=/usr/local/bin/ mode=770

  - name: install idm base packages
    yum: name={{ item }} state=present
    with_items:
      - python2-pyasn1-0.1.9-7.el7.noarch
      - vim-enhanced
      - tmux
      - openssh-clients
      - expect 
      - ntp
      - ipa-server-dns
      - ipa-server
      - bind 
      - bind-dyndb-ldap
...
