---
osrelease: 3.10.14-1.git.0.ba8ae6d
installer_release: 3.10.21-1.git.0.6446011

ose_packages:
  - vim
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - dnsmasq
  - openshift-ansible-{{ installer_release }}.el7.noarch
  - openshift-ansible-playbooks-{{ installer_release }}.el7.noarch
  - openshift-ansible-roles-{{ installer_release }}.el7.noarch
  - openshift-ansible-docs-{{ installer_release }}.el7.noarch
  - atomic-openshift-{{ osrelease }}.el7.x86_64
  - atomic-openshift-excluder-{{ osrelease }}.el7.noarch
  - atomic-openshift-docker-excluder-{{ osrelease }}.el7.noarch
  - atomic-openshift-clients-{{ osrelease }}.el7.x86_64

storage_packages:
  - nfs-utils
  - glusterfs-fuse
  - ceph-common
  - iscsi-initiator-utils
  - device-mapper-multipath

...
