- name: pull webssh2 image from quay
  docker_image:
    name: quay.io/thoraxe/webssh2:180809

- name: create webssh2 systemd service
  copy:
    src: webssh2.service
    dest: /etc/systemd/system/

- name: create webssh2 config
  template:
    src: webssh2.j2
    dest: /etc/sysconfig/webssh2
    owner: root
    group: root
    mode: 0644
