apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tektonconfig-patch-clusterrole
rules:
- apiGroups: ["operator.tekton.dev"]
  resources: ["tektonconfigs"]
  verbs: ["patch"]
