---

  - name: install ose base packages
    yum: name={{ item }} state=present
    with_items:
      - vim
      - wget
      - git
      - net-tools
      - bind-utils
      - etcd
      - iptables-services
      - bridge-utils
      - bash-completion
      - atomic-openshift-clients
      - atomic-openshift-utils
      - atomic-openshift-excluder-3.5.5.26-1.git.0.276cbb4.el7
      - atomic-openshift-docker-excluder-3.5.5.26-1.git.0.276cbb4.el7

  - name: install ose storage packages
    yum: name={{ item }} state=present
    with_items:
      - nfs-utils
      - glusterfs-fuse
      - ceph-common
      - iscsi-initiator-utils

  - name: remove openshift packages from filter
    shell: atomic-openshift-excluder unexclude

  - name: restart docker
    service: name=docker state=restarted

  - name: create iptables config
    copy: src=iptables dest=/etc/sysconfig/

  - name: restart iptables 
    service: name=iptables state=restarted enabled=yes

  - name: stop firewalld 
    service: name=firewalld state=stopped enabled=no


...
