---
- name: add password based user
  user:
    name: student
    state: present
    password: $6$bhFt7ggi$SMQ8rYcB7vAm9hghHbMaLyfDq721tBC5JlIyoeHBDeMrcKeL7U9KOQybbXBC.v4EHk0QwXxTwEKc4FbytwA5K 
    group: wheel
    append: yes


- name: force allowed ssh access
  shell: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"

...
