---

  - name: install docker
    yum: name=docker state=present

  - name: create docker storage config
    copy: src=docker-storage-setup dest=/etc/sysconfig/

  - name: start docker
    service: name=docker state=started enabled=yes

  - name: install registry
    yum: name=docker-distribution state=present
...
