---

- hosts: glusterfs

  tasks:

  - name: configure firewall for gluster-block
    shell: "iptables {{ item }}"
    with_items:
      - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24010 -j ACCEPT"
      - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 3260 -j ACCEPT"
      - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT"

  - name: persist firewall config for gluster-block
    lineinfile:
      path: /etc/sysconfig/iptables
      line: "{{ item }}"
      insertafter: "^:OS_FIREWALL_ALLOW"
    with_items:
      - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24010 -j ACCEPT"
      - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 3260 -j ACCEPT"
      - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT"

...
